# Generated by Django 5.0.1 on 2024-01-30 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_todoitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todoitem",
            old_name="list",
            new_name="parent_list",
        ),
    ]
